// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping_2d/proto/cell_limits.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cartographer/mapping_2d/proto/cell_limits.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping_2d {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* CellLimits_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CellLimits_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto() {
  protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cartographer/mapping_2d/proto/cell_limits.proto");
  GOOGLE_CHECK(file != NULL);
  CellLimits_descriptor_ = file->message_type(0);
  static const int CellLimits_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellLimits, num_x_cells_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellLimits, num_y_cells_),
  };
  CellLimits_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CellLimits_descriptor_,
      CellLimits::default_instance_,
      CellLimits_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellLimits, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellLimits, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CellLimits));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CellLimits_descriptor_, &CellLimits::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto() {
  delete CellLimits::default_instance_;
  delete CellLimits_reflection_;
}

void protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n/cartographer/mapping_2d/proto/cell_lim"
    "its.proto\022\035cartographer.mapping_2d.proto"
    "\"6\n\nCellLimits\022\023\n\013num_x_cells\030\001 \001(\005\022\023\n\013n"
    "um_y_cells\030\002 \001(\005", 136);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/mapping_2d/proto/cell_limits.proto", &protobuf_RegisterTypes);
  CellLimits::default_instance_ = new CellLimits();
  CellLimits::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto {
  StaticDescriptorInitializer_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto() {
    protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto();
  }
} static_descriptor_initializer_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CellLimits::kNumXCellsFieldNumber;
const int CellLimits::kNumYCellsFieldNumber;
#endif  // !_MSC_VER

CellLimits::CellLimits()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CellLimits::InitAsDefaultInstance() {
}

CellLimits::CellLimits(const CellLimits& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CellLimits::SharedCtor() {
  _cached_size_ = 0;
  num_x_cells_ = 0;
  num_y_cells_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CellLimits::~CellLimits() {
  SharedDtor();
}

void CellLimits::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CellLimits::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CellLimits::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CellLimits_descriptor_;
}

const CellLimits& CellLimits::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2fcell_5flimits_2eproto();
  return *default_instance_;
}

CellLimits* CellLimits::default_instance_ = NULL;

CellLimits* CellLimits::New() const {
  return new CellLimits;
}

void CellLimits::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    num_x_cells_ = 0;
    num_y_cells_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CellLimits::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 num_x_cells = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_x_cells_)));
          set_has_num_x_cells();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_num_y_cells;
        break;
      }

      // optional int32 num_y_cells = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_num_y_cells:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_y_cells_)));
          set_has_num_y_cells();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CellLimits::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 num_x_cells = 1;
  if (has_num_x_cells()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_x_cells(), output);
  }

  // optional int32 num_y_cells = 2;
  if (has_num_y_cells()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num_y_cells(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CellLimits::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 num_x_cells = 1;
  if (has_num_x_cells()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_x_cells(), target);
  }

  // optional int32 num_y_cells = 2;
  if (has_num_y_cells()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num_y_cells(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CellLimits::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 num_x_cells = 1;
    if (has_num_x_cells()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_x_cells());
    }

    // optional int32 num_y_cells = 2;
    if (has_num_y_cells()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_y_cells());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CellLimits::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CellLimits* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CellLimits*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CellLimits::MergeFrom(const CellLimits& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_num_x_cells()) {
      set_num_x_cells(from.num_x_cells());
    }
    if (from.has_num_y_cells()) {
      set_num_y_cells(from.num_y_cells());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CellLimits::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CellLimits::CopyFrom(const CellLimits& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CellLimits::IsInitialized() const {

  return true;
}

void CellLimits::Swap(CellLimits* other) {
  if (other != this) {
    std::swap(num_x_cells_, other->num_x_cells_);
    std::swap(num_y_cells_, other->num_y_cells_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CellLimits::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CellLimits_descriptor_;
  metadata.reflection = CellLimits_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)
