// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping_2d/proto/probability_grid.proto

#ifndef PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping_2d/proto/map_limits.pb.h"
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping_2d {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto();

class ProbabilityGrid;

// ===================================================================

class ProbabilityGrid : public ::google::protobuf::Message {
 public:
  ProbabilityGrid();
  virtual ~ProbabilityGrid();

  ProbabilityGrid(const ProbabilityGrid& from);

  inline ProbabilityGrid& operator=(const ProbabilityGrid& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProbabilityGrid& default_instance();

  void Swap(ProbabilityGrid* other);

  // implements Message ----------------------------------------------

  ProbabilityGrid* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProbabilityGrid& from);
  void MergeFrom(const ProbabilityGrid& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.mapping_2d.proto.MapLimits limits = 1;
  inline bool has_limits() const;
  inline void clear_limits();
  static const int kLimitsFieldNumber = 1;
  inline const ::cartographer::mapping_2d::proto::MapLimits& limits() const;
  inline ::cartographer::mapping_2d::proto::MapLimits* mutable_limits();
  inline ::cartographer::mapping_2d::proto::MapLimits* release_limits();
  inline void set_allocated_limits(::cartographer::mapping_2d::proto::MapLimits* limits);

  // repeated int32 cells = 2;
  inline int cells_size() const;
  inline void clear_cells();
  static const int kCellsFieldNumber = 2;
  inline ::google::protobuf::int32 cells(int index) const;
  inline void set_cells(int index, ::google::protobuf::int32 value);
  inline void add_cells(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cells() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cells();

  // repeated int32 update_indices = 3;
  inline int update_indices_size() const;
  inline void clear_update_indices();
  static const int kUpdateIndicesFieldNumber = 3;
  inline ::google::protobuf::int32 update_indices(int index) const;
  inline void set_update_indices(int index, ::google::protobuf::int32 value);
  inline void add_update_indices(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      update_indices() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_update_indices();

  // optional int32 max_x = 4;
  inline bool has_max_x() const;
  inline void clear_max_x();
  static const int kMaxXFieldNumber = 4;
  inline ::google::protobuf::int32 max_x() const;
  inline void set_max_x(::google::protobuf::int32 value);

  // optional int32 max_y = 5;
  inline bool has_max_y() const;
  inline void clear_max_y();
  static const int kMaxYFieldNumber = 5;
  inline ::google::protobuf::int32 max_y() const;
  inline void set_max_y(::google::protobuf::int32 value);

  // optional int32 min_x = 6;
  inline bool has_min_x() const;
  inline void clear_min_x();
  static const int kMinXFieldNumber = 6;
  inline ::google::protobuf::int32 min_x() const;
  inline void set_min_x(::google::protobuf::int32 value);

  // optional int32 min_y = 7;
  inline bool has_min_y() const;
  inline void clear_min_y();
  static const int kMinYFieldNumber = 7;
  inline ::google::protobuf::int32 min_y() const;
  inline void set_min_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping_2d.proto.ProbabilityGrid)
 private:
  inline void set_has_limits();
  inline void clear_has_limits();
  inline void set_has_max_x();
  inline void clear_has_max_x();
  inline void set_has_max_y();
  inline void clear_has_max_y();
  inline void set_has_min_x();
  inline void clear_has_min_x();
  inline void set_has_min_y();
  inline void clear_has_min_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cartographer::mapping_2d::proto::MapLimits* limits_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cells_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > update_indices_;
  ::google::protobuf::int32 max_x_;
  ::google::protobuf::int32 max_y_;
  ::google::protobuf::int32 min_x_;
  ::google::protobuf::int32 min_y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto();

  void InitAsDefaultInstance();
  static ProbabilityGrid* default_instance_;
};
// ===================================================================


// ===================================================================

// ProbabilityGrid

// optional .cartographer.mapping_2d.proto.MapLimits limits = 1;
inline bool ProbabilityGrid::has_limits() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProbabilityGrid::set_has_limits() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProbabilityGrid::clear_has_limits() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProbabilityGrid::clear_limits() {
  if (limits_ != NULL) limits_->::cartographer::mapping_2d::proto::MapLimits::Clear();
  clear_has_limits();
}
inline const ::cartographer::mapping_2d::proto::MapLimits& ProbabilityGrid::limits() const {
  return limits_ != NULL ? *limits_ : *default_instance_->limits_;
}
inline ::cartographer::mapping_2d::proto::MapLimits* ProbabilityGrid::mutable_limits() {
  set_has_limits();
  if (limits_ == NULL) limits_ = new ::cartographer::mapping_2d::proto::MapLimits;
  return limits_;
}
inline ::cartographer::mapping_2d::proto::MapLimits* ProbabilityGrid::release_limits() {
  clear_has_limits();
  ::cartographer::mapping_2d::proto::MapLimits* temp = limits_;
  limits_ = NULL;
  return temp;
}
inline void ProbabilityGrid::set_allocated_limits(::cartographer::mapping_2d::proto::MapLimits* limits) {
  delete limits_;
  limits_ = limits;
  if (limits) {
    set_has_limits();
  } else {
    clear_has_limits();
  }
}

// repeated int32 cells = 2;
inline int ProbabilityGrid::cells_size() const {
  return cells_.size();
}
inline void ProbabilityGrid::clear_cells() {
  cells_.Clear();
}
inline ::google::protobuf::int32 ProbabilityGrid::cells(int index) const {
  return cells_.Get(index);
}
inline void ProbabilityGrid::set_cells(int index, ::google::protobuf::int32 value) {
  cells_.Set(index, value);
}
inline void ProbabilityGrid::add_cells(::google::protobuf::int32 value) {
  cells_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ProbabilityGrid::cells() const {
  return cells_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ProbabilityGrid::mutable_cells() {
  return &cells_;
}

// repeated int32 update_indices = 3;
inline int ProbabilityGrid::update_indices_size() const {
  return update_indices_.size();
}
inline void ProbabilityGrid::clear_update_indices() {
  update_indices_.Clear();
}
inline ::google::protobuf::int32 ProbabilityGrid::update_indices(int index) const {
  return update_indices_.Get(index);
}
inline void ProbabilityGrid::set_update_indices(int index, ::google::protobuf::int32 value) {
  update_indices_.Set(index, value);
}
inline void ProbabilityGrid::add_update_indices(::google::protobuf::int32 value) {
  update_indices_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ProbabilityGrid::update_indices() const {
  return update_indices_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ProbabilityGrid::mutable_update_indices() {
  return &update_indices_;
}

// optional int32 max_x = 4;
inline bool ProbabilityGrid::has_max_x() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProbabilityGrid::set_has_max_x() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProbabilityGrid::clear_has_max_x() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProbabilityGrid::clear_max_x() {
  max_x_ = 0;
  clear_has_max_x();
}
inline ::google::protobuf::int32 ProbabilityGrid::max_x() const {
  return max_x_;
}
inline void ProbabilityGrid::set_max_x(::google::protobuf::int32 value) {
  set_has_max_x();
  max_x_ = value;
}

// optional int32 max_y = 5;
inline bool ProbabilityGrid::has_max_y() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProbabilityGrid::set_has_max_y() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProbabilityGrid::clear_has_max_y() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProbabilityGrid::clear_max_y() {
  max_y_ = 0;
  clear_has_max_y();
}
inline ::google::protobuf::int32 ProbabilityGrid::max_y() const {
  return max_y_;
}
inline void ProbabilityGrid::set_max_y(::google::protobuf::int32 value) {
  set_has_max_y();
  max_y_ = value;
}

// optional int32 min_x = 6;
inline bool ProbabilityGrid::has_min_x() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ProbabilityGrid::set_has_min_x() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ProbabilityGrid::clear_has_min_x() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ProbabilityGrid::clear_min_x() {
  min_x_ = 0;
  clear_has_min_x();
}
inline ::google::protobuf::int32 ProbabilityGrid::min_x() const {
  return min_x_;
}
inline void ProbabilityGrid::set_min_x(::google::protobuf::int32 value) {
  set_has_min_x();
  min_x_ = value;
}

// optional int32 min_y = 7;
inline bool ProbabilityGrid::has_min_y() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ProbabilityGrid::set_has_min_y() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ProbabilityGrid::clear_has_min_y() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ProbabilityGrid::clear_min_y() {
  min_y_ = 0;
  clear_has_min_y();
}
inline ::google::protobuf::int32 ProbabilityGrid::min_y() const {
  return min_y_;
}
inline void ProbabilityGrid::set_min_y(::google::protobuf::int32 value) {
  set_has_min_y();
  min_y_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2fprobability_5fgrid_2eproto__INCLUDED
