// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping_2d/proto/range_data_inserter_options.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cartographer/mapping_2d/proto/range_data_inserter_options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping_2d {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* RangeDataInserterOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RangeDataInserterOptions_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto() {
  protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cartographer/mapping_2d/proto/range_data_inserter_options.proto");
  GOOGLE_CHECK(file != NULL);
  RangeDataInserterOptions_descriptor_ = file->message_type(0);
  static const int RangeDataInserterOptions_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RangeDataInserterOptions, hit_probability_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RangeDataInserterOptions, miss_probability_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RangeDataInserterOptions, insert_free_space_),
  };
  RangeDataInserterOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RangeDataInserterOptions_descriptor_,
      RangeDataInserterOptions::default_instance_,
      RangeDataInserterOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RangeDataInserterOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RangeDataInserterOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RangeDataInserterOptions));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RangeDataInserterOptions_descriptor_, &RangeDataInserterOptions::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto() {
  delete RangeDataInserterOptions::default_instance_;
  delete RangeDataInserterOptions_reflection_;
}

void protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\?cartographer/mapping_2d/proto/range_da"
    "ta_inserter_options.proto\022\035cartographer."
    "mapping_2d.proto\"h\n\030RangeDataInserterOpt"
    "ions\022\027\n\017hit_probability\030\001 \001(\001\022\030\n\020miss_pr"
    "obability\030\002 \001(\001\022\031\n\021insert_free_space\030\003 \001"
    "(\010", 202);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/mapping_2d/proto/range_data_inserter_options.proto", &protobuf_RegisterTypes);
  RangeDataInserterOptions::default_instance_ = new RangeDataInserterOptions();
  RangeDataInserterOptions::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto {
  StaticDescriptorInitializer_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto() {
    protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto();
  }
} static_descriptor_initializer_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RangeDataInserterOptions::kHitProbabilityFieldNumber;
const int RangeDataInserterOptions::kMissProbabilityFieldNumber;
const int RangeDataInserterOptions::kInsertFreeSpaceFieldNumber;
#endif  // !_MSC_VER

RangeDataInserterOptions::RangeDataInserterOptions()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RangeDataInserterOptions::InitAsDefaultInstance() {
}

RangeDataInserterOptions::RangeDataInserterOptions(const RangeDataInserterOptions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RangeDataInserterOptions::SharedCtor() {
  _cached_size_ = 0;
  hit_probability_ = 0;
  miss_probability_ = 0;
  insert_free_space_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RangeDataInserterOptions::~RangeDataInserterOptions() {
  SharedDtor();
}

void RangeDataInserterOptions::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RangeDataInserterOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RangeDataInserterOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RangeDataInserterOptions_descriptor_;
}

const RangeDataInserterOptions& RangeDataInserterOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto();
  return *default_instance_;
}

RangeDataInserterOptions* RangeDataInserterOptions::default_instance_ = NULL;

RangeDataInserterOptions* RangeDataInserterOptions::New() const {
  return new RangeDataInserterOptions;
}

void RangeDataInserterOptions::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    hit_probability_ = 0;
    miss_probability_ = 0;
    insert_free_space_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RangeDataInserterOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double hit_probability = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &hit_probability_)));
          set_has_hit_probability();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_miss_probability;
        break;
      }

      // optional double miss_probability = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_miss_probability:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &miss_probability_)));
          set_has_miss_probability();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_insert_free_space;
        break;
      }

      // optional bool insert_free_space = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_insert_free_space:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &insert_free_space_)));
          set_has_insert_free_space();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RangeDataInserterOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional double hit_probability = 1;
  if (has_hit_probability()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->hit_probability(), output);
  }

  // optional double miss_probability = 2;
  if (has_miss_probability()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->miss_probability(), output);
  }

  // optional bool insert_free_space = 3;
  if (has_insert_free_space()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->insert_free_space(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RangeDataInserterOptions::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional double hit_probability = 1;
  if (has_hit_probability()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->hit_probability(), target);
  }

  // optional double miss_probability = 2;
  if (has_miss_probability()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->miss_probability(), target);
  }

  // optional bool insert_free_space = 3;
  if (has_insert_free_space()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->insert_free_space(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RangeDataInserterOptions::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double hit_probability = 1;
    if (has_hit_probability()) {
      total_size += 1 + 8;
    }

    // optional double miss_probability = 2;
    if (has_miss_probability()) {
      total_size += 1 + 8;
    }

    // optional bool insert_free_space = 3;
    if (has_insert_free_space()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RangeDataInserterOptions::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RangeDataInserterOptions* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RangeDataInserterOptions*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RangeDataInserterOptions::MergeFrom(const RangeDataInserterOptions& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_hit_probability()) {
      set_hit_probability(from.hit_probability());
    }
    if (from.has_miss_probability()) {
      set_miss_probability(from.miss_probability());
    }
    if (from.has_insert_free_space()) {
      set_insert_free_space(from.insert_free_space());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RangeDataInserterOptions::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RangeDataInserterOptions::CopyFrom(const RangeDataInserterOptions& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RangeDataInserterOptions::IsInitialized() const {

  return true;
}

void RangeDataInserterOptions::Swap(RangeDataInserterOptions* other) {
  if (other != this) {
    std::swap(hit_probability_, other->hit_probability_);
    std::swap(miss_probability_, other->miss_probability_);
    std::swap(insert_free_space_, other->insert_free_space_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RangeDataInserterOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RangeDataInserterOptions_descriptor_;
  metadata.reflection = RangeDataInserterOptions_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)
